### ISSUE TITLE
Find a way to print new reports to different sheets in CSV

### ISSUE THREAD

**Issue by outyprouty** [umbc-research/trackingCode#1]
This may not be possible, google is your friend :)

**Comment by ckragh02** [comment]
Not possible in .csv files :(

As of writing this, I have great (maybe) idea:
Output to Excel file, automagically convert and upload excel file to drive as a sheets file
Will share results here when results exist

**Comment by ckragh02** [comment]
> Not possible in .csv files :(
> 
> As of writing this, I have great (maybe) idea: Output to Excel file, automagically convert and upload excel file to drive as a sheets file Will share results here when results exist

(immediately after posting realized this may not be able to append sheets to old sheets file, will see what I can do)

**Comment by ckragh02** [comment]
Never mind, same issue as noted on RT ticket, no access to google APIs through school email

**Comment by outyprouty** [comment]
Let's keep code-related issues in github.

As for output, just output a CSV. Pandas should have fairly native support for that from a dataframe.

**Comment by outyprouty** [comment]
I think it is OK to have separate runs in different sheets. We can always ask someone else to go through a few files and combine them -- getting the data those files present is the hard part.

**Comment by ckragh02** [comment]
> Let's keep code-related issues in github.
> 
> As for output, just output a CSV. Pandas should have fairly native support for that from a dataframe.

This is currently how the code works, wasn't sure if you had any other ideas for automating the process, closing this issue for now

**Comment by ckragh02** [comment]
This is currently how the code works, wasn't sure if you had any other ideas for automating the process, closing this issue for now
